// *** Gamedesign.nl global curseword listing

function hasCurseword(thisCurseword)
{
	thisCurseword = thisCurseword.toLowerCase();

	var rtrim = /^[\s\uFEFF ]+|[\s\uFEFF ]+$/g;
	thisCurseword = thisCurseword.replace(rtrim, '');
	thisCurseword = thisCurseword.replace(/\s/g, '');

	cursewordPresent = false;

	if(thisCurseword.indexOf('.') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf(',') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('@') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('#') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('$') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('%') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('^') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('&') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('*') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('(') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf(')') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('_') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('-') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('+') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('=') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('{') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('}') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('|') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('/') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('`') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('~') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('slet') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('fuck') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('hitler') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('hoer') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('lik lul') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('lik kut') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('dildo') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('spermalikker') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('neuken') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('balzak') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('homo') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('penis') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('bentgay') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('is een down') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('klootzak') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('dikzak') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('piemol') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('scheit') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('neuk') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('geil') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('tering') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('tiefus') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('sex') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('megooltje') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('heeft down') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('pino pik') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('poepdrol') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('idioot') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('ballenlikker') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('poepen') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('sukkel') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('nattepoes') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('jij lul') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('piemel') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('poepzooi') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('schijt') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('kakje') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('papzak') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('bekvolijzer') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('kutkut') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('vagina') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('kutlul') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('lesbie') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('oetlul') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('kutje') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('lelijke') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('lullelikker') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('poepbenjij') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('poeperd') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('lelijkehond') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('jemoeder') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('kutspel') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('pornhub') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('schijtzooi') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('lullo') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('moffen') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('dikkelul') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('gekkechinees') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('dikke lul') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('is stom') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('poeper') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('in je kont') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('poepmens') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('papa likker') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('mama likker') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('porno') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('pijpen') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('de pedo') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('n.e.u.k.e.n') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('poepje') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('stront') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('kutkinderen') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('shitvoer') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('kanker') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('holyshit') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('n.eu.k') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('poepchinees') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('poepihoofd') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('n.e.u.k.e.r') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('l.u.l') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('f*cker') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('poepinbroek') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('k.u.t') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('kakzooi') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('poepman') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('kakhoofd') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('f*ck') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('kutdaan') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('poepzak') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('poepie') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('hondenlul') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('kankker') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('kutzooi') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('poephoofd') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('poepboy') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('is gay') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('poepsmoel') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('lekkerpoep') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('sperma') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('kut kind') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('harigkut') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('is kut') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('porn') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('kutkind') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('flikker') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('akbar') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('kutsarah') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('rotzak') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('poepineenschoen') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('stom') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('gek') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('rot') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('neuk') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('seks') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('lesbie') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('geil') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('fuck') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('fuk') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('lul') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('kut') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('bal') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('zak') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('piemol') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('piemel') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('pimol') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('pimel') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('pik') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('scheet') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('stront') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('poep') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('moeder') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('lesbie') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('sperm') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('maf') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('schijt') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('scheit') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('pis') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('plas') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('klote') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('kloot') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('kont') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('pijp') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('zeur') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('poep') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('pies') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('nicht') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('flikker') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('flicker') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('homo') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('dikke') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('stijve') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('schaam') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('bitch') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('pedo') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('tiete') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('gatver') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('gotver') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('getver') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('gay') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('godver') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('god') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('shit') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('haat') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('natte') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('stijf') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('achterlijk') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('pielemuis') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('drol') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('sekx') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('dood') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('verkracht') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('*') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('pi3m3l') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('pi3mel') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('piem3l') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('foking') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('fawk you') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('likker') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('kakspel') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('anus') >= 0) cursewordPresent = true;
	
	if(thisCurseword.indexOf('n3uk') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('beft') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('beffen') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf(' bef ') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('nigger') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('neger') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('condoom') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf(' lik ') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('fakka') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('fack') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('cutje') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('penes') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('nege3r') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('nigg3r') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('duivel') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('sugardaddy') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('sugardady') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('nuek') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('daddy') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('suck') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('zuig') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf(' lik ') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('penus') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('balle') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('ballen') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('likmij') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('dickpick') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('dickpik') >= 0) cursewordPresent = true;
	if(thisCurseword.indexOf('digpick') >= 0) cursewordPresent = true;
	

	return(cursewordPresent);
}